# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa1b743319a2e09f222168977897ea101fc98bc41395d0c8a02702003517826c34d3cb47316734cfd78dcdea9b4ddc2925ec9eb904cd867ec50a33c46b60660

test:
  secret_key_base: 6d1c63828e871c0207b6bc52a03bff572e833a18c61791a9c1b138d4129d613e1f78f7abf9b67c95b92a4d620e9022dd293185226012a82a9c8b30cfa9a27734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
